///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class EpisodeListModelObjectListLinksSelf {
/*
{
  "href": "https://api.tvmaze.com/episodes/1"
} 
*/

  String? href;

  EpisodeListModelObjectListLinksSelf({
    this.href,
  });
  EpisodeListModelObjectListLinksSelf.fromJson(Map<String, dynamic> json) {
    href = json["href"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["href"] = href;
    return data;
  }
}

class EpisodeListModelObjectListLinks {
/*
{
  "self": {
    "href": "https://api.tvmaze.com/episodes/1"
  }
} 
*/

  EpisodeListModelObjectListLinksSelf? self;

  EpisodeListModelObjectListLinks({
    this.self,
  });
  EpisodeListModelObjectListLinks.fromJson(Map<String, dynamic> json) {
    self = (json["self"] != null)
        ? EpisodeListModelObjectListLinksSelf.fromJson(json["self"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (self != null) {
      data["self"] = self!.toJson();
    }
    return data;
  }
}

class EpisodeListModelObjectListImage {
/*
{
  "medium": "https://static.tvmaze.com/uploads/images/medium_landscape/1/4388.jpg",
  "original": "https://static.tvmaze.com/uploads/images/original_untouched/1/4388.jpg"
} 
*/

  String? medium;
  String? original;

  EpisodeListModelObjectListImage({
    this.medium,
    this.original,
  });
  EpisodeListModelObjectListImage.fromJson(Map<String, dynamic> json) {
    medium = json["medium"]?.toString();
    original = json["original"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["medium"] = medium;
    data["original"] = original;
    return data;
  }
}

class EpisodeListModelObjectList {
/*
{
  "id": 1,
  "url": "https://www.tvmaze.com/episodes/1/under-the-dome-1x01-pilot",
  "name": "Pilot",
  "season": 1,
  "number": 1,
  "type": "regular",
  "airdate": "2013-06-24",
  "airtime": "22:00",
  "airstamp": "2013-06-25T02:00:00+00:00",
  "runtime": 60,
  "image": {
    "medium": "https://static.tvmaze.com/uploads/images/medium_landscape/1/4388.jpg",
    "original": "https://static.tvmaze.com/uploads/images/original_untouched/1/4388.jpg"
  },
  "summary": "<p>When the residents of Chester's Mill find themselves trapped under a massive transparent dome with no way out, they struggle to survive as resources rapidly dwindle and panic quickly escalates.</p>",
  "_links": {
    "self": {
      "href": "https://api.tvmaze.com/episodes/1"
    }
  }
} 
*/

  int? id;
  String? url;
  String? name;
  int? season;
  int? number;
  String? type;
  String? airdate;
  String? airtime;
  String? airstamp;
  int? runtime;
  EpisodeListModelObjectListImage? image;
  String? summary;
  EpisodeListModelObjectListLinks? Links;

  EpisodeListModelObjectList({
    this.id,
    this.url,
    this.name,
    this.season,
    this.number,
    this.type,
    this.airdate,
    this.airtime,
    this.airstamp,
    this.runtime,
    this.image,
    this.summary,
    this.Links,
  });
  EpisodeListModelObjectList.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    url = json["url"]?.toString();
    name = json["name"]?.toString();
    season = json["season"]?.toInt();
    number = json["number"]?.toInt();
    type = json["type"]?.toString();
    airdate = json["airdate"]?.toString();
    airtime = json["airtime"]?.toString();
    airstamp = json["airstamp"]?.toString();
    runtime = json["runtime"]?.toInt();
    image = (json["image"] != null)
        ? EpisodeListModelObjectListImage.fromJson(json["image"])
        : null;
    summary = json["summary"]?.toString();
    Links = (json["_links"] != null)
        ? EpisodeListModelObjectListLinks.fromJson(json["_links"])
        : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["url"] = url;
    data["name"] = name;
    data["season"] = season;
    data["number"] = number;
    data["type"] = type;
    data["airdate"] = airdate;
    data["airtime"] = airtime;
    data["airstamp"] = airstamp;
    data["runtime"] = runtime;
    if (image != null) {
      data["image"] = image!.toJson();
    }
    data["summary"] = summary;
    if (Links != null) {
      data["_links"] = Links!.toJson();
    }
    return data;
  }
}

class EpisodeListModel {
/*
{
  "ObjectList": [
    {
      "id": 1,
      "url": "https://www.tvmaze.com/episodes/1/under-the-dome-1x01-pilot",
      "name": "Pilot",
      "season": 1,
      "number": 1,
      "type": "regular",
      "airdate": "2013-06-24",
      "airtime": "22:00",
      "airstamp": "2013-06-25T02:00:00+00:00",
      "runtime": 60,
      "image": {
        "medium": "https://static.tvmaze.com/uploads/images/medium_landscape/1/4388.jpg",
        "original": "https://static.tvmaze.com/uploads/images/original_untouched/1/4388.jpg"
      },
      "summary": "<p>When the residents of Chester's Mill find themselves trapped under a massive transparent dome with no way out, they struggle to survive as resources rapidly dwindle and panic quickly escalates.</p>",
      "_links": {
        "self": {
          "href": "https://api.tvmaze.com/episodes/1"
        }
      }
    }
  ]
} 
*/

  List<EpisodeListModelObjectList?>? ObjectList;

  EpisodeListModel({
    this.ObjectList,
  });
  EpisodeListModel.fromJson(Map<String, dynamic> json) {
    if (json["ObjectList"] != null) {
      final v = json["ObjectList"];
      final arr0 = <EpisodeListModelObjectList>[];
      v.forEach((v) {
        arr0.add(EpisodeListModelObjectList.fromJson(v));
      });
      ObjectList = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (ObjectList != null) {
      final v = ObjectList;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["ObjectList"] = arr0;
    }
    return data;
  }
}
